apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
    image:
      repository: pihole/pihole
      tag: "latest"
      pullPolicy: IfNotPresent
    nodeSelector:
      kubernetes.io/agent: "true"
    dnsHostPort:
      enabled: false
    serviceDns:
      type: ClusterIP
      port: 53
    serviceWeb:
      http:
        enabled: true
        port: 80
        nodePort: 30080
      type: NodePort
    persistentVolumeClaim:
      enabled: false
    adminPassword: "your-secure-password" # Replace with a strong password
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: pihole.local
          paths:
            - path: /
              pathType: Prefix
